[project]
name = "file-system"
version = "0.1.0"
description = "File management MCP server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.2.6",
    "mcp[cli]>=1.7.1",
    "ruff>=0.11.8",
]

