[project]
name = "mcp-client-manual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "griffe>=1.7.3",
    "loguru>=0.7.3",
    "mcp>=1.9.3",
    "mistralai>=1.8.1",
    "yfinance>=0.2.61",
]
